[package]
name = "fast-socks5"
version = "0.4.0"
authors = ["Jonathan Dizdarevic <dizzda@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Fast SOCKS5 client/server implementation written in Rust async/.await (with async-std)"
repository = "https://github.com/dizda/fast-socks5"

[dependencies]
futures = "0.3.8"
log = "0.4"
async-std = { version = "1.8.0", features = ["default"] }
anyhow = "1.0"
thiserror = "1.0"

# Dependencies for examples/
[dev-dependencies]
env_logger = "0.7"
structopt = "0.3"

[[example]]
name = "server"

[[example]]
name = "client"

[[example]]
name = "simple_tcp_server"
