[package]
name = "fast-socks5"
version = "0.1.1"
authors = ["Jonathan Dizdarevic <dizzda@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Fast SOCKS5 client/server implementation written in Rust async/.await (with async-std)"

[dependencies]
futures = "0.3"
log = "0.4"
async-std = { version = "1.4", features = ["default", "unstable"] }
anyhow = "1.0"
thiserror = "1.0"
structopt = "0.3"

# Dependencies for examples/
[dev-dependencies]
env_logger = "0.7"

[[example]]
name = "server"

[[example]]
name = "client"
